### ISSUE TITLE
Question: up to which solidity version does qtum support?

### ISSUE THREAD

**Issue by yuanfeiz** [qtumproject/qtum#246]

**Comment by Earlz** [comment]
Because we are compatible with the EVM we support all versions of solidity
that currently exist

On Jul 24, 2017 10:12 AM, "YuanfΞi Zhu" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/qtumproject/qtum/issues/246>, or mute the thread

**Comment by yuanfeiz** [comment]
Great! So up to 0.4.11? Including the `require` and `assert`?

**Comment by Earlz** [comment]
Yes, of course. There are currently no Solidity features that are incompatible with Qtum's implementation of the EVM
