### ISSUE TITLE
Qtum-0.14.3 unsigned.dmg

### ISSUE THREAD

**Issue by kimbovee** [qtumproject/qtum#380]
This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by YessirreeBob** [comment]
This is a common hiccup when downloading a program that Mac OS doesn't recognize. It's easy to get around it.

First, try again to open the .dmg file.
Then:
1) Open Settings
2) Open Security and Privacy
3) Go the 'General' tab
4) Towards the bottom of the menu you'll see that is has blocked you from opening the .dmg file because it's from an "unknown developer"
4) Choose to Allow the opening of the program

That should do it!

**Comment by kimbovee** [comment]
OK, I think I got it downloaded. But there's no address or private key. How am I suppose to send qtum to this wallet if there's no address ?

Sent from my Verizon 4G LTE Smartphone

----- Reply message -----

**Comment by Earlz** [comment]
Go to the receive tab and push "request payment" to get a new address (all the text fields are optional). If you have any further problems please reopen this issue

**Comment by kimbovee** [comment]
Now that I have transferred qtum to the new wallet version, what exchange can I go onto to exchange for etherium? Please help.

Sent from my Verizon 4G LTE Smartphone

----- Reply message -----
