### ISSUE TITLE
error installing qtum on vps

### ISSUE THREAD

**Issue by bereska** [qtumproject/qtum#413]
ubuntu@ip-172-31-46-217:~/qtum$ make -j1
Making all in src
make[1]: Entering directory '/home/ubuntu/qtum/src'
make[2]: Entering directory '/home/ubuntu/qtum/src'
  CXXLD    libbitcoinconsensus.la
copying selected object files to avoid basename conflicts...
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
virtual memory exhausted: Cannot allocate memory
Makefile:8827: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 1
make[2]: Leaving directory '/home/ubuntu/qtum/src'
Makefile:13327: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/qtum/src'
Makefile:692: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
ubuntu@ip-172-31-46-217:~/qtum$ free -m
              total        used        free      shared  buff/cache   available
Mem:            990          46         878           6          65         828
Swap:             0           0           0
### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by bereska** [comment]
does it have anything to do with the security settings on my vps? should i edit inbound rules to open all traffic? now it is limited to my current location ip via ssh

**Comment by mikehash** [comment]
Hi Bereska, 
The issue is low ram, see where it says: "virtual memory exhausted: Cannot allocate memory". I also noticed you don't have swap enabled, most VPS don't create a swap file by default so I'd recommend doing the following:

```
dd if=/dev/zero of=/swapfile bs=1M count=3000
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile none swap defaults 0 0" >> /etc/fstab
```
This creates a swap file which will help you build and run Qtum.
The commands create the swap, give proper permissions, enable the swap and activate it on boot time in case your VPS restarts.
Please try the above, it'll solve your issue.

**Comment by bereska** [comment]
Hi Mikehash, thanks for prompt reply. Sure, i'll try try that. Could you also give me ALL requirements for VPS to stake qtum? Memory (you just covered that), disk space, security settings, etc. I want to configure it the way it could stake qtum at least for a year from now. I am on AWS Linux free tier right now.

**Comment by bereska** [comment]
actually, it would be great if you could post this kind of information in your tutorials so people could set it all up easily and promptly without waiting for you replies for days. If you want to us to invest in qtum of course. Can anyone answer my question above before the weekend?

**Comment by mikehash** [comment]
1gb Ram is more than enough for staking Qtum. However you do need more than that to compile qtum (around 2gb ram is needed).
Any 20GB disk will suffice for a while, Qtum is quite new and the blockchain is only 245mb right now. 

Any VPS will do, AWS is among the best of course, but due to the low ram in the free instance, you need a swap file to help out during build.
Regarding security, there's many tutorials and how-tos online, it really depends on which distribution you're using. 
You can take a look at this one if you're using ubuntu
https://www.thefanclub.co.za/how-to/how-secure-ubuntu-1604-lts-server-part-1-basics

**Comment by bereska** [comment]
thank you
