### ISSUE TITLE
Virus Found on Windows Download

### ISSUE THREAD

**Issue by kdsmith34** [qtumproject/qtum#495]
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
I tried to download the Windows 64 Qtum wallet a few times and my Windows Defender Antivirus on my computer says that there is a Trojan associated with the download. What can I do? Is there another wallet I can use?

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Qtum are you using?
List the version number/commit ID
I went to the latest download link. I also went to the Qtum website to try to download.
### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Illasera** [comment]
I would speculate that qtum core wallet was forked from bitcoin core wallet and uses some of its code.

Bitcoin core wallet was marked by a lot of anti-viruses as malware because it had a miner in it , and some botnets used it to mine bitcoin on zombie machines (Machines that were infected by a malware that allowed crackers to remotely control it), Theregoes if qtum shares the same code, it also shares parts of the sub-signatures of that code and is also branded accordingly as a malware.

**Comment by itcodes** [comment]
很正常的原因。忽略即可！！！
