### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by HamiltonWang** [qtumproject/qtum#580]
I read this article 
https://medium.com/@jb395official/testnet-and-qtum-mainnet-performance-january-1-8-e7af03a5d430?source=linkShare-e4ec3fe25e9e-1530316659

I’m evaluating Qtum for an industry that requires high performance smart contract. So I’m wondering how many transaction can Qtum take per sec and what is the latency for confirmation? 

I’m aware that this question depends largely on CPU, number of nodes and many other factors. But I just need to know the range it may fall into. For example, 10k/sec or 1k/s or 0.1k/s. For latency, what is the latency be like if there are x number of nodes. 

If there is no such data, I may be able to try to test them by myself if codes for building private network and spawning of clients is readily available.

Thanks

**Comment by JB395** [comment]
Hello Hamilton, I wrote that article and while not on the Qtum Team, I have researched and blogged about the Qtum Mainchain performance since it launched in September last year.

Qtum currently has 70 transactions per second, but these can be doubled by using on-chain governance doubling the block size. Those transactions can hold many smart contract calls, I have seen up to 200 token transfers in a transaction. I would also note that Qtum was launched with SegWit enabled, and has Lightening Network in its future.

The average block spacing for Qtum is 144 seconds, and this number has not changed from 40 nodes at launch to the current 7,500, and will not change with the nodes CPUs. Qtum block publishing relies on a random lottery process such that block spacing will be random between a few seconds up to 10 - 15 minutes in the extreme, with an average of 144 seconds. Qtum uses Proof of Stake consensus, so low power hardware, such as a Raspberry Pi is capable of running a full node. 

Please let me know if you are looking for more specific data, I may have published it previously.

**Comment by HamiltonWang** [comment]
Btw, any specific use case that is the best fit for QTUM?

**Comment by JB395** [comment]
Use cases: smart contracts for distributed applications, mobile transactions using SPV, creating simple smart contracts on mobile. Work in progress: adding the x86 virtual machine for smart contract programming in well-known mature languages.

Qtum is fully decentralized. Every transaction is validated by every node relaying that transaction on the network and every block is validated by every node. Every contract call is executed by every node. If a contract create call or other contract call was formulated as a proper transaction it would be propagated (and executed) by the nodes in the network. There is no validation that code in a smart contract is correct or proper, that is up to the contract developer.
