### ISSUE TITLE
Staking issues

### ISSUE THREAD

**Issue by Crypto2** [qtumproject/qtum#713]
2 staking issues to report:

1. listsinceblock/listtransactions report staking rewards as category 'receive' with no indication of it being staking rewards so we had to turn it off since we had no way to tell if it was a real deposit or just staking reward.

2. Even though staking has been off (confirmed by getstakinginfo and debug.log) we got a reward today in https://qtum.info/tx/c636a4b974bcaad5de06c32f47794ec273575f407689f6f60b9dfa7b58dbc841
The input address isn't one of ours so not sure if it's possible to earn PoS even when we aren't staking ourselves?

**Comment by qtum-neil** [comment]
1. The way staking works is it spends a utxo and sends the same amount+reward to the same address that the utxo was spent from, the way to determine if it's staked coins or a received coins using `listtransactions` is to look at `blockindex`, if it equals 1 then it's staked coins, if it is strictly greater than 1 then it's received coins, the reason is that staking rewards will always be put as the second transaction in a block (first is coinbase, which is empty for PoS blocks, second is coinstake, then other transactions are put in the block).

2. Qtum uses Mutualized Proof Of Stake, the rewards are distributed over 10 blocks, the first 1/10 is paid in the found block, the rest is paid after 500 blocks over 9 blocks, 1/10 is paid 9 times.

**Comment by Crypto2** [comment]
Our staking has been off over a week though, not sure why we'd still be getting rewards?
