### ISSUE TITLE
staking in regtest

### ISSUE THREAD

**Issue by XinyaYang0506** [qtumproject/qtum#718]
I am running qtum-0.17.6-aarch64-linux-gnu on regtest mode. I have passed the mature process and the blocks and balances are keeping growing for several days. However, there are still some questions I am confused about: 
1. although the staking weight of each node is far beyond 1000.00000000, the ```netstakeweight``` is still 0 (or 0.2 if using ```getmininginfo```) when I review the staking info. Maybe because of this, the difficulty level and the expected time are very very low now. 
2. I want to be able to control how much to stake or whether to participate in staking or not because I want to test on the robustness of the system. However, I could not find the suitable command for this, can someone give me a hint?
3. Is there a good way to manually adjust the difficulty level?

Here is the terminal record: 
```$ ./qtum-cli -regtest getstakinginfo
{
  "enabled": true,
  "staking": true,
  "errors": "",
  "currentblocktx": 0,
  "pooledtx": 0,
  "difficulty": 4.656542373906925e-10,
  "search-interval": -4,
  "weight": 16930701000406000,
  "netstakeweight": 0,
  "expectedtime": 0
}
```

ps. I am using ubuntu 64 bit on Raspberry Pi

**Comment by JB395** [comment]
Hello Xinya Yang,
Qtum, including regest, generates the first 5,000 blocks as Proof of Work, where the difficulty is held low by the code for fast generation. For example, you can use the command “`generate 1000`” to make 1,000 new blocks in a minute. Otherwise, code limits the block creation to every 30 seconds. I wouldn’t look at any of the staking parameters for blocks below 5,001.

Above block 5001, blocks switch to block rewards of 2,000 and continue at two per minute, so they may be Proof of Stake blocks (some of the staking parameters start to work), but the staking behavior still seems controlled.

You may consider looking at staking on Qtum Testnet, which has correct staking behavior on a live test blockchain. https://github.com/qtumproject/documents/blob/master/en/Testnet-User-Guide.md

**Comment by XinyaYang0506** [comment]
Hi Jack!
I just generated blocks to reach above 5000. (I thought the threshold is 500. :>) However, the ```netstakeweight``` is still 0 (or about 0.03 if by ```getminginginfo```). 
The result I got: 
```
$ qtum-cli -regtest getmininginfo
{
  "blocks": 7564,
  "currentblockweight": 4000,
  "currentblocktx": 0,
  "difficulty": {
    "proof-of-work": 4.656542373906925e-10,
    "proof-of-stake": 4.656542373906925e-10,
    "search-interval": 32
  },
  "blockvalue": 2000000000000,
  "netmhashps": 6.666565736122815e-08,
  "netstakeweight": 0.03430152927590586,
  "errors": "",
  "networkhashps": 1.230769230769231,
  "pooledtx": 0,
  "stakeweight": {
    "minimum": 10876000000000000,
    "maximum": 0,
    "combined": 10876000000000000
  },
  "chain": "regtest",
  "warnings": ""
}
```
Also, is it possible to adjust the difficulty level, the block generation rate?  Is it possible to know who is the winner of a particular block? 
I really want to be able to observe the staking process in regtest mode, because it is more under control. 

Thank you for your response! (also if the profile picture is the same, thx for your medium post too!)

**Comment by JB395** [comment]
More on this. If you run the blocks into Proof of Stake territory ( > 5001 ), but have a single node, it still won't give interesting results because it will stake with 100% of the network weight and win all the block rewards. When I did this, the regtest node was still getting fixed block rewards (2,000 - 20,000 QTUM) at regular intervals.

You may want to explore a network of regtest nodes, such as with https://steemit.com/qtum/@cryptominder/qtum-blockchain-development-environment-setup. If you can network several regest nodes together on the same local blockchain, the block rewards should be allocated based on the relative amount of coins staking on each node. If this runs like the main networks, when you connect multiple nodes, difficulty is adjusted with each block as compared to the target block spacing of 128 seconds. If you decide to run this on Docker, use this more current version https://github.com/qtumproject/qtum-docker.

**Comment by XinyaYang0506** [comment]
I set up a network successfully! I just checked, and the last block has a proof of stake flag. However, what do you mean by "spacing of 128 secs"? (Totally a English question). Does that mean that the block generation rate is uncontrollable? Still, is it possible to know the winner node of the block? Thank you~!

**Comment by JB395** [comment]
Excellent progress, may be better and more interactive to jump on Discord or Telegram, depending on your preference.

The normal consensus algorithm will adjust the difficulty/target for each new block to try and achieve a 128 second average block time, but random variation could be between 16 seconds and 10 - 20 minutes. Not sure if regtest operates the same way networked though.

If you can get the latest transaction ID, there is a sequence that will give the addresses:
gettransaction <transaction ID>    < get the blockhash
getblock <blockhash>  <- take the 2nd transaction, the blockstake (PoS block rewards)
gettransaction <transaction ID>  <- get the long hex string here
decoderawtransaction <long hex string>

you will see vouts, the first one empty, the 2nd and 3rd probably the stake (split in half) with the block reward winner address, the next 9 for block reward winners starting 501 block previous. For example, here qShevnU8B6hSSVAfkTmSTintCJ7zZMcUzQ won the block reward. 

```
 "vout": [
    {
      "value": 0.00000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "",
        "hex": "",
        "type": "nonstandard"
      }
    },
    {
      "value": 6500.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "0220defc1871e8261f199219450544039a06f0f95f7c4d3d3c8ca68e62f16371f0 OP_CHECKSIG",
        "hex": "210220defc1871e8261f199219450544039a06f0f95f7c4d3d3c8ca68e62f16371f0ac",
        "reqSigs": 1,
        "type": "pubkey",
        "addresses": [
          "qShevnU8B6hSSVAfkTmSTintCJ7zZMcUzQ"
        ]
      }
    },
    {
      "value": 6500.00000000,
      "n": 2,
      "scriptPubKey": {
        "asm": "0220defc1871e8261f199219450544039a06f0f95f7c4d3d3c8ca68e62f16371f0 OP_CHECKSIG",
        "hex": "210220defc1871e8261f199219450544039a06f0f95f7c4d3d3c8ca68e62f16371f0ac",
        "reqSigs": 1,
        "type": "pubkey",
        "addresses": [
          "qShevnU8B6hSSVAfkTmSTintCJ7zZMcUzQ"
        ]
      }
    },
    {
      "value": 2000.00000000,
      "n": 3,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 1c5901d61292d52755f476763c83ef572482b23b OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9141c5901d61292d52755f476763c83ef572482b23b88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "qL9GhjFkeFx3QVWJtqxYriSJEtcJ7gSocf"
        ]
      }
    },

```

This is about block 7,150 regtest

**Comment by JB395** [comment]
More on this per Earlz, regtest will always make new blocks at fixed intervals. Probably two a minute for every node on your network. You can see the block structure and mechanics on regtest, and then true dynamics on Testnet.

**Comment by XinyaYang0506** [comment]
Hi Jack, 
I was assigned some other works and busy on that so sorry for the late response! Can I add you on Telegram? Although there will be little work assigned to me about Qtum in the future, I would like to explore more and clear all my confusions. Thx! (telegram user name same as github username)

**Comment by JB395** [comment]
Sure, I sent you a direct message. I am @JB_365 on Telegram
