### ISSUE TITLE
Transaction sent on Qtum Core version mainnet-ignition-v0.14.16 (64-bit) did not get to destination

### ISSUE THREAD

**Issue by faisalharianawalla** [qtumproject/qtum#864]
Sent QTUM tokens transaction from old QTUM Wallet to Binance. 
Qtum Core version mainnet-ignition-v0.14.16 (64-bit)

**Expected behavior**

 Should have approx. 10 QTUM in wallet.

**Actual behavior**

 Transaction in limbo shows as sent but uncomfirmed.

**To reproduce**

  What should I do to make this transaction work?

**System information**

 
Qtum Core version mainnet-ignition-v0.14.16 (64-bit)

 OS Windows 10

 Windows 10

 Status: 475 confirmations
Date: 10/1/2020 19:26
To: Test Transaction 1 QQXWjkyirM4FJnJv8Jr7nC3HtMFXx56hbn
Debit: -9.91909600 QTUM
Transaction fee: -0.00090400 QTUM
Net amount: -9.92000000 QTUM
Transaction ID: 01446d114c8a48b72ebc033d14a8ecb0abfaa282b5d8753f5337dec08194f62d
Transaction total size: 225 bytes
Output index: 0

**Comment by faisalharianawalla** [comment]
Hello I am tried to move my QTUM to Binance wallet. It did not transfer to Binance wallet is there something that I should be doing such as upgrading my wallet to the newer versions before I can use it? I have around 10 QTUM in limbo right now how do I get these back? Any assistance is greatly appreciated. I don't know which upgrade wallet I should be upgrading to and don't know how to do this if I need to do that ....

**Comment by JB395** [comment]
Hello faisalharianawalla,

Qtum has had two mandatory hard forks since the version 0.14 wallet. This means your old version wallet is operating on a split side chain which is not connected to Qtum mainnet, exchanges, etc.

There are several steps to recover which can be summarized as 1. Make a good backup of the wallet, a copy of the wallet.dat file, 2. update to the latest version of the Qtum Core wallet, 3. delete the local copy of the blockchain and resync the whole thing, 4. run the "zapwallettxes=2" command on startup. This should cancel out the pending transaction, restore your full balance, and restore normal operation.

Please see more details about these recovery steps for

Windows: https://blog.qtum.org/hard-fork-special-windows-2c8febdbcd43
Mac: https://blog.qtum.org/hard-fork-special-mac-462e11a879d1
Linux and Raspberry Pi: https://blog.qtum.org/hard-fork-special-linux-raspberry-pi-40e60341923d

Hope this helps, please let us know how it works.

**Comment by faisalharianawalla** [comment]
Hi Jack thanks a million for your help so I followed everything but one thing that did not happen was that the 9.9 QTUM that I sent was not reinstated to my account. I'll try the Zap thing again and let you know what happens. Hopefully it works the second time...

**Comment by faisalharianawalla** [comment]
The TX went through but no Steked toens show in wallet

**Comment by JB395** [comment]
Make sure when you run the "zapwallettxes=2" command that it says "Rescanning..." with the Qtum-Qt GUI wallet. This shows you entered the command correctly.

Any block rewards received on the split side chain remain on that split chain and are worthless.

**Comment by Earlz** [comment]
Closing as this seems to be answered
